/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_nus_service                    19
#define gattdb_nus_rx                         21
#define gattdb_nus_tx                         23
#define gattdb_ras                            25
#define gattdb_ras_features                   27
#define gattdb_ras_real_time_ranging_data     29
#define gattdb_ras_real_time_cccd             30
#define gattdb_ras_on_demand_ranging_data     32
#define gattdb_ras_on_demand_cccd             33
#define gattdb_ras_cp                         35
#define gattdb_ras_cp_cccd                    36
#define gattdb_ras_ranging_data_ready         38
#define gattdb_ras_ranging_data_ready_cccd    39
#define gattdb_ras_ranging_data_overwritten   41
#define gattdb_ras_ranging_data_overwritten_cccd 42

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_name_len                14
#define gattdb_nus_service_len                16
#define gattdb_nus_rx_len                     20
#define gattdb_nus_tx_len                     20
#define gattdb_ras_len                        2


#endif // __GATT_DB_H
